### ISSUE TITLE
reconsider the split of reproducible research lesson

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor_training#19]
Splitting reproducible research into two parts might not be great. Each part will then be short, and each group discussing each half will not get a full overview of the lesson. Maybe better to repeat one lesson twice? Maybe let participants vote!

**Comment by bast** [comment]
Would it be a problem to discuss this lesson only in one session - in other words no splitting and no repeating? Or would it not fit into one session?

**Comment by wikfeldt** [comment]
it would not be a problem, it's just that we then end up with 8 lessons to distribute over three sessions. I think we can have a popular vote so that participants can choose which lesson to repeat in the last slot

**Comment by bast** [comment]
We also have the branch design lesson which somehow fell under the table which we could use. Vote is also a good idea.

**Comment by wikfeldt** [comment]
fixed in https://github.com/coderefinery/coderefinery.org/pull/293
closing this issue
