### ISSUE TITLE
split intro episode in two

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor_training#27]
i think it'll be better to have one "what is coderefinery" episode and one "coderefinery/carpentry teaching style". More logical separation

**Comment by annefou** [comment]
Splitting the intro is very good. The only thing that is weird now is that we have "Mental Models and Formative Assessment" in 02-teachingstyle (this is where we defined what is a novice, competent practionner and expert) but we already discuss target audience in episode-1 01-intro/
Should we rephrase it in episode 1 to avoid talking about notions that we only introduce in episode 2?

**Comment by wikfeldt** [comment]
yeah I thought about this, and my idea was that it would be fine to leave the precise definition of "novice" and "competent practitioner" to the 2nd episode, and leave a note that "Novices and competent practitioners will be more clearly defined in the next section."

After all the rough meaning of the concepts are already somewhat obvious, i.e. one understands that it relates to a beginner and a more advanced user.

But maybe it can be clarified further?

**Comment by annefou** [comment]
Yes. I will simplify it in the first episode. There is no need to use any jargon to explain that CodeRefinery workshops are best for those who already code on a regular basis.

**Comment by wikfeldt** [comment]
first episode now split in three. Anne working on follow-up improvements. closing
