### ISSUE TITLE
more instructors should add their training philosophies

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor_training#30]
like Anne has done in https://coderefinery.github.io/instructor_training/01-intro/
(but this section is changing in https://github.com/coderefinery/instructor_training/pull/28)

**Comment by bast** [comment]
Thanks! I will contribute to this Thu/Fri this week.

**Comment by bast** [comment]
We have now a couple. More welcome. I am closing now the issue to keep focus on those where we still have to do something.
