### ISSUE TITLE
too much repetition of "CodeRefinery"

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor_training#34]
the lesson is named "CodeRefinery for contributors and instructors" (should it be renamed? e.g. "CodeRefinery instructor training")
and then we have episodes called 
- The CodeRefinery project
- CodeRefinery approach to teaching
- Running CodeRefinery workshops
- Contributing to CodeRefinery Lesson development
- Teaching CodeRefinery lessons

I suggest we remove some or all of the "CodeRefinery" mentions from the episode titles

**Comment by bast** [comment]
> I suggest we remove some or all of the "CodeRefinery" mentions from the episode titles

I agree.
