### ISSUE TITLE
Enough time for exercise in lightning overview?

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor_training#49]
There is an exercise in the "lightning overview" session:
https://coderefinery.github.io/instructor_training/03-lightningoverview/#exercise-learning-objectives

In the lesson we say 20 minutes, on the workshop page 30, but in either scenario I see no time for any group discussion exercise. I think we can be happy if we manage to present these and not go over time.

**Comment by wikfeldt** [comment]
i agree, we don't need an exercise at the end of this episode

**Comment by bast** [comment]
I agree. I will transplant it to there.
